### PR TITLE
Editcommand shows specific error when attempting to edit subject

### LINKED ISSUE #169: [edit_student] edit_student command should show specific error when attempting to edit subjects
### Description

When attempting to edit a student's subjects using the command `edit_student 1 s/`, the system returns a generic invalid command message instead of a specific error explaining that editing subjects is not allowed.

**Current Behavior:**

Input:

```
edit_student 1 s/
```

Output:
```
Invalid command format!
edit_student: Edits the details of the student identified by the index number used in the displayed student list. Existing values will be overwritten by the input values.
Parameters: INDEX (must be a positive integer) [n/NAME] [p/PHONE] [e/EMAIL] [a/ADDRESS]...
```

**Expected Behavior:**

The system should display a specific error message indicating that editing subjects is not supported, for example:

```
Error: Editing subjects directly is not allowed. Use [add_subject] or [remove_subject] commands instead.
```

### Steps to Reproduce

1. Execute the command `edit_student 1 s/` (or any index with `s/` prefix).
2. Observe the generic error message instead of a subject-specific warning.

### Suggested Fix

- Update the input validation to detect the `s/` parameter and return a more helpful error message.
- Consider adding this restriction to the command's help text for clarity.

### Additional Context

- This improves user experience by providing clear guidance on how to modify subjects.

### PR DESCRIPTION
**Pull request by nicholasohjj**
Resolves #169

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/EditStudentCommand.java [hunk 1]
```diff
@@ -78,7 +79,7 @@ public CommandResult execute(Model model) throws CommandException {
         Student studentToEdit = lastShownList.get(index.getZeroBased());
         Student editedStudent = createEditedStudent(studentToEdit, editStudentDescriptor);
 
-        if (!studentToEdit.isSameStudent(editedStudent) && model.hasStudent(editedStudent)) {
+        if (!studentToEdit.equals(editedStudent) && model.hasStudent(editedStudent)) {
```
Comment (GZTan23) [inline src/main/java/seedu/address/logic/commands/EditStudentCommand.java:82]: This is going to create an inconsistency because the `model#hasStudent` uses `student#isSameStudent`

**Review by GZTan23 — COMMENTED** [review]
Everything else looks good 👍

File: src/main/java/seedu/address/logic/commands/EditStudentCommand.java (hunk 1 above)
Comment (nicholasohjj) [reply src/main/java/seedu/address/logic/commands/EditStudentCommand.java]: Reverted

**Review by GZTan23 — APPROVED** [review]
LGTM
