### PR TITLE
Modify dateparser to use dd-MM-yyyy

### LINKED ISSUE #178: [add_assignment] Date format error message contradicts UG specification
### Current Behavior

**Command Executed**:

```
add_assignment 1 as/Math HW d/15-10-2023
```

**Actual Output**:

```
Error: Dates should be in the format: D-M-YYYY and after the current date
```

**Observed Issues**:

1. Format contradiction:
    - UG specifies `DD-MM-YYYY` format
    - Error message shows `D-M-YYYY` (inconsistent)
2. Strict future date requirement not documented
3. Two validation concerns combined in one error message

### Expected Behavior

**For format DD-MM-YYYY**:
```
add_assignment 1 as/Math HW d/15-10-2023 → Success
```

**For invalid format**:

```
Error: Date must be in DD-MM-YYYY format
```

**For past dates** (if enforced):

```
Warning: Due date is in the past - proceed anyway? [Y/N]
```

**Documentation Requirements**:

- Clearly specify format in UG Parameters section
- Document date validation rules

---

### Reproduction Steps

1. Execute with UG-specified format:
    
    ```
    add_assignment 1 as/Math HW d/15-10-2023
    ```
    
2. Observe format rejection despite UG compliance
3. Try alternative formats to identify accepted patterns

---

### Impact Analysis

- **User Confusion**: Contradicts documented specifications
- **Workflow Block**: Valid dates rejected unnecessarily
- **Data Limitations**: Prevents historical assignment tracking

---

### Suggested Fix

1. Update date parser to accept `DD-MM-YYYY`:

```
// In AssignmentDate class
private static final String DATE_PATTERN = "dd-MM-yyyy";
```

1. Separate validation messages:

```
if (!isValidFormat(dateStr)) {
    throw new ParseException("Date must be in DD-MM-YYYY format");
}
if (isPastDate(parsedDate) && !allowPastDates) {
    throw new ParseException("Due date cannot be in the past");
}
```

1. Update UG to explicitly state:

```
d/DATE: Must be in DD-MM-YYYY format (e.g. 15-10-2023)
```

<html>
<body>
<h3>Test Cases</h3>

Input | Expected Result
-- | --
d/15-10-2023 | Success
d/5-10-2023 | Success (or consistent format error)
d/15/10/2023 | Format error
d/2023-10-15 | Format error
d/15-13-2023 | Invalid date error

</body>
</html>

### PR DESCRIPTION
**Pull request by nicholasohjj**
Resolves #178

### CODE REVIEW

**Comment by nicholasohjj** [comment]
Resolves #179

File: src/main/java/seedu/address/model/datetimeutil/Date.java [hunk 1]
```diff
@@ -13,9 +13,9 @@
  */
 public class Date implements Comparable<Date> {
 
-    public static final String MESSAGE_CONSTRAINTS = "Dates should be in the format: D-M-YYYY and "
+    public static final String MESSAGE_CONSTRAINTS = "d/DATE: Must be in DD-MM-YYYY format (e.g. 15-10-2023) and"
             + "after the current date";
-    public static final DateTimeFormatter VALID_FORMAT = DateTimeFormatter.ofPattern("d-M-yyyy");
+    public static final DateTimeFormatter VALID_FORMAT = DateTimeFormatter.ofPattern("dd-MM-yyyy");
```
Comment (GZTan23) [inline src/main/java/seedu/address/model/datetimeutil/Date.java:18]: This should be kept the same, so that even if the user inputs 5-1-2023, it would still work, rather than restricting it to 05-01-2023. This would be overzealous input validation.

File: src/test/java/seedu/address/model/lesson/DateTest.java [hunk 2]
```diff
@@ -16,7 +16,7 @@ class DateTest {
 
     @Test
     void isValidDate() {
-        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("d-M-yyyy");
+        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd-MM-yyyy");
```
Comment (GZTan23) [inline src/test/java/seedu/address/model/lesson/DateTest.java:19]: This is the same as the other one

File: src/main/java/seedu/address/model/assignment/Assignment.java [hunk 3]
```diff
@@ -13,8 +13,10 @@
  */
 public class Assignment implements Comparable<Assignment> {
 
-    public static final String MESSAGE_CONSTRAINTS = "Assignment names should be alphanumeric";
-    //This regex is generated by ChatGPT
+    public static final String MESSAGE_CONSTRAINTS = "Assignment names should be alphanumeric "
+            + "and can contain spaces, apostrophes, ampersands, and hyphens. "
+            + "It should not exceed 50 characters.";
```
Comment (GZTan23) [inline src/main/java/seedu/address/model/assignment/Assignment.java:18]: The regex does not allow for any symbols other than spaces.

**Review by GZTan23 — CHANGES_REQUESTED** [review]
Other changes look fine

File: src/main/java/seedu/address/model/datetimeutil/Date.java (hunk 1 above)
Comment (nicholasohjj) [reply src/main/java/seedu/address/model/datetimeutil/Date.java:18]: dd-MM-yyyy aligns with UG. d-M-yyy is causing discrepancy with UG. strict input validation for date

File: src/test/java/seedu/address/model/lesson/DateTest.java (hunk 2 above)
Comment (nicholasohjj) [reply src/test/java/seedu/address/model/lesson/DateTest.java:19]: as above

File: src/main/java/seedu/address/model/assignment/Assignment.java (hunk 3 above)
Comment (nicholasohjj) [reply src/main/java/seedu/address/model/assignment/Assignment.java:18]: seems fine to me to prevent bugs

File: src/main/java/seedu/address/logic/parser/ParserUtil.java [hunk 4]
```diff
@@ -165,7 +166,7 @@ public static String parseAssignmentName(String assignmentName) throws ParseExce
         requireNonNull(assignmentName);
         String trimmedAssignmentName = assignmentName.trim();
         if (!Subject.isValidSubjectName(trimmedAssignmentName)) {
-            throw new ParseException(Subject.MESSAGE_CONSTRAINTS);
+            throw new ParseException(Assignment.MESSAGE_CONSTRAINTS);
```
[the remark this answers is not in the document]
Comment (nicholasohjj) [reply src/main/java/seedu/address/logic/parser/ParserUtil.java]: Fix in latest commit

File: src/main/java/seedu/address/logic/parser/AddAssignmentCommandParser.java [hunk 5]
```diff
@@ -22,20 +22,27 @@ public class AddAssignmentCommandParser implements Parser<AddAssignmentCommand>
      * @throws ParseException if the user input does not conform the expected format
      */
     public AddAssignmentCommand parse(String args) throws ParseException {
-        requireNonNull(args);
```
[the remark this answers is not in the document]
Comment (nicholasohjj) [reply src/main/java/seedu/address/logic/parser/AddAssignmentCommandParser.java:25]: Logic is already implemented under Parserutil


`        Index index = ParserUtil.parseIndex(argMultimap.getPreamble());
        String assignmentName = ParserUtil.parseAssignmentName(argMultimap.getValue(PREFIX_ASSIGNMENT).orElse(""));
        Date dueDate = ParserUtil.parseDate(argMultimap.getValue(PREFIX_DATE).orElse(""));

`

File: src/main/java/seedu/address/model/datetimeutil/Date.java (hunk 1 above)
Comment (GZTan23) [reply src/main/java/seedu/address/model/datetimeutil/Date.java:18]: I think we should edit the UG to match this instead, to allow for more flexibility on the user's end

File: src/main/java/seedu/address/model/assignment/Assignment.java (hunk 3 above)
Comment (GZTan23) [reply src/main/java/seedu/address/model/assignment/Assignment.java:18]: I just tested on your branch and the command does not allow for apostrophes, ampersands and hyphens. It only allows for spaces, so I'm a bit confused on the part on trying to prevent bugs

File: src/main/java/seedu/address/model/datetimeutil/Date.java (hunk 1 above)
Comment (nicholasohjj) [reply src/main/java/seedu/address/model/datetimeutil/Date.java]: resolved in latest commit

File: src/test/java/seedu/address/model/lesson/DateTest.java (hunk 2 above)
Comment (nicholasohjj) [reply src/test/java/seedu/address/model/lesson/DateTest.java]: resolved

**Review by GZTan23 — APPROVED** [review]
Looks good 👍
